spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        
  flyway:
    validate-on-migrate: true
    
logging:
  level:
    com.fleetops: INFO
    org.springframework: WARN
    org.hibernate: WARN
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
