# Default configuration (dev profile)
spring:
  profiles:
    active: dev
  application:
    name: fleetops-backend
    
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetops_dev
    username: fleetops
    password: fleetops
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        # Let Hibernate auto-detect PostGIS dialect
        # dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
        jdbc:
          time_zone: UTC
          
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}
          
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,quartz
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    com.fleetops: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    
app:
  jwt:
    secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}
    expiration: 86400000 # 24 hours
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
